import {
  ArchiveRestore,
  Bell,
  BookOpen,
  Brain,
  Building,
  Calendar,
  CalendarDays,
  ChartNoAxesColumnIncreasing,
  Presentation,
  ClipboardList,
  Cpu,
  FileCheck,
  FileText,
  FlaskConical,
  GitBranch,
  Globe,
  GraduationCap,
  History,
  Key,
  LayoutDashboard,
  Megaphone,
  MessageCircle,
  Rows3,
  Settings,
  ShieldCheck,
  Target,
  Telescope,
  TrendingUp,
  Upload,
  User,
  UserCheck,
  UserCog,
  Users,
  Wrench
} from "lucide-react";

export const STUDENT_NAV = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard, badge: null },
  { id: "my-research", label: "My Research", icon: FlaskConical, badge: null },
  { id: "research-timeline", label: "Research Timeline", icon: GitBranch, badge: null },
  { id: "thesis-upload", label: "Thesis Upload", icon: Upload, badge: null },
  { id: "chapter-versions", label: "Chapter Versions", icon: History, badge: null },

  { id: "ai-assistant", label: "AI Assistant", icon: Brain, badge: "AI" },

  { id: "proposal-generator", label: "Proposal Generator", icon: FileText, badge: "AI" },

  { id: "literature", label: "Literature Review", icon: BookOpen, badge: "AI" },

 { id: "meetings", label: "Meeting Schedule", icon: Calendar, badge: null },
  { id: "guide-comments", label: "Guide Comments", icon: MessageCircle, badge: null },
  { id: "progress", label: "Progress Tracker", icon: Target, badge: null },
  { id: "notifications", label: "Notifications", icon: Bell, badge: null },
  { id: "profile", label: "Profile", icon: User, badge: null },
  { id: "settings", label: "Settings", icon: Settings, badge: null },
];

export const GUIDE_NAV = [
  { id: "dashboard",         label: "Dashboard",           icon: LayoutDashboard, badge: null },
  { id: "assigned-students", label: "Assigned Students",   icon: GraduationCap,   badge: "12" },
  { id: "thesis-reviews",    label: "Thesis Reviews",      icon: FileCheck,       badge: "5"  },
  { id: "pending-approvals", label: "Pending Approvals",   icon: ClipboardList,   badge: "3"  },
  { id: "ai-review",         label: "AI Review Assistant", icon: Brain,           badge: "AI" },
  { id: "meeting-scheduler", label: "Meeting Scheduler",   icon: Calendar,        badge: null },
  { id: "research-progress", label: "Research Progress",   icon: TrendingUp,      badge: null },
  { id: "notifications",     label: "Notifications",       icon: Bell,            badge: "6"  },
  { id: "reports",           label: "Reports",             icon: ChartNoAxesColumnIncreasing,       badge: null },
  { id: "profile",           label: "Profile",             icon: User,            badge: null },
  { id: "settings",          label: "Settings",            icon: Settings,        badge: null },
];

export const ADMIN_NAV = [
  { id: "dashboard",          label: "Dashboard",           icon: LayoutDashboard, badge: null },
  { id: "user-management",    label: "User Management",     icon: Users,           badge: null },
  { id: "student-management", label: "Student Management",  icon: GraduationCap,   badge: null },
  { id: "guide-management",   label: "Guide Management",    icon: UserCheck,       badge: null },
  { id: "hod-management",     label: "HOD Management",      icon: ShieldCheck,     badge: null },
  { id: "college-admin-management", label: "College Admins", icon: UserCog,        badge: null },
  { id: "department-mgmt",    label: "Departments",         icon: Building,        badge: null },
  { id: "university-mgmt",    label: "University",          icon: Globe,           badge: null },
  { id: "research-topics",    label: "Research Topics",     icon: Telescope,       badge: null },
  { id: "ai-playground",      label: "AI Playground",       icon: Brain,           badge: null },
  { id: "ai-config",          label: "AI Configuration",    icon: Cpu,             badge: null },
  { id: "analytics",          label: "Reports & Analytics", icon: ChartNoAxesColumnIncreasing,       badge: null },
  { id: "notifications",      label: "Notifications",       icon: Bell,            badge: "8"  },
  { id: "audit-logs",         label: "Audit Logs",          icon: ShieldCheck,     badge: null },
  { id: "backup-restore",     label: "Backup & Restore",    icon: ArchiveRestore,  badge: null },
  { id: "system-settings",    label: "System Settings",     icon: Wrench,          badge: null },
  { id: "roles-permissions",  label: "Roles & Permissions", icon: Key,             badge: null },
  { id: "academic-years",     label: "Academic Years",      icon: CalendarDays,    badge: null },
  { id: "semesters",          label: "Semesters",            icon: Rows3,            badge: null },
  { id: "faculties",          label: "Faculties",            icon: Presentation,    badge: null },
  { id: "global-announcements", label: "Announcements",     icon: Megaphone,       badge: null },
  { id: "profile",            label: "Profile",             icon: User,            badge: null },
];

export const HOD_NAV = [
  { id: "dashboard",          label: "Dashboard",           icon: LayoutDashboard, badge: null },
  { id: "students",           label: "Students",            icon: GraduationCap,   badge: null },
  { id: "guides",             label: "Guides",              icon: UserCheck,       badge: null },
  { id: "allocations",        label: "Allocations",         icon: ClipboardList,   badge: null },
  { id: "research-topics",    label: "Research Topics",     icon: Telescope,       badge: null },
  { id: "announcements",      label: "Announcements",       icon: Megaphone,       badge: null },
  { id: "reports",            label: "Reports",             icon: ChartNoAxesColumnIncreasing,       badge: null },
  { id: "notifications",      label: "Notifications",       icon: Bell,            badge: null },
  { id: "profile",            label: "Profile",             icon: User,            badge: null },
];
